name: form_validate
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  path_provider: ^2.1.3
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.8
  image_picker: ^1.0.5
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1
  top_snackbar_flutter: ^3.1.0
  overlay_support: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
