name: form_validate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  path_provider: ^2.1.3
  intl: ^0.20.2
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.6

  # State management (optional)
  provider: ^6.1.1

  # Notifications (optional for future features)
  flutter_local_notifications: ^17.2.1+2

  # Calendar widget (optional)
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
